name: Aura
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  modal_progress_hud_nsn: ^0.3.0
  shared_preferences: ^2.1.2
  geolocator: ^9.0.2
  permission_handler: 10.3.0
  geocoding: ^2.1.0
  firebase_database: ^10.2.2
  intl: 0.18.1
  dio: 5.2.0+1
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.7.0
  syncfusion_flutter_charts: ^20.3.61
  flutter: 
    sdk: flutter
  fluttertoast: ^8.2.2

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  flutter_lints: ^1.0.0

flutter: 
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Regular.ttf

